# Generated by Django 4.2.16 on 2024-11-27 10:09

import random
from django.db import migrations


def forwards_func(apps, schema_editor):
    Country = apps.get_model("app", "Country")
    CustomUser = apps.get_model("app", "CustomUser")

    for country in Country.objects.all():
        user = random.choice(CustomUser.objects.all())
        country.my_user = user
        country.save()


def reverse_func(apps, schema_editor):
    Country = apps.get_model("app", "Country")
    # CustomUser = apps.get_model('app', 'CustomUser')

    for country in Country.objects.all():
        country.my_user = None
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
